
txt2img:
  "sd_model_key": "runwayml/stable-diffusion-v1-5"
  "ip_adapter_image_path": 
  "prompt": "UVmap, (blue and white porcelain:1.3), teapot, high quality"
  "negative_prompt": "blur, low quality, noisy image, over-exposed"
  "seed": -1
  "width": 1024
  "height": 1024
  "num_images_per_prompt": 1
  "guidance_scale": 7.0
  "num_inference_steps": 20
  "controlnet_units":
    - "preprocessor": "none"
      "controlnet_key": "GeorgeQi/Paint3d_UVPos_Control"
      "condition_image_path":
      "weight": 1.0